# Generated by Django 3.2.8 on 2021-10-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_game', models.CharField(max_length=30)),
                ('name', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
    ]
